academy/urls.py
import debug_toolbar
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers

from games.views import (
    CustomAuthToken,
    GameViewSet,
    InfoViewSet,
    PlayerStatViewSet,
    RankedFacecardsView,
    UserViewSet,
)

router = routers.DefaultRouter()
router.register("users", UserViewSet)
router.register("games", GameViewSet)
router.register("ranked_cards", RankedFacecardsView, basename="ranked_cards")
router.register("stats", PlayerStatViewSet, basename="stats")
router.register("info", InfoViewSet, basename="info")


urlpatterns = [
    path("", include("web.urls")),
    path("api/", include(router.urls)),
    path("admin/", admin.site.urls),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path("api-token-auth/", CustomAuthToken.as_view()),
    path("__debug__/", include(debug_toolbar.urls)),
    path("webpush/", include("webpush.urls")),
]

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.urls import path

import web.views as views

urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("games/", views.GameListView.as_view(), name="game_list"),
    path("games/rss/", views.GamesFeed(), name="games_feed"),
    path("games/<int:pk>/", views.GameDetailView.as_view(), name="game_detail"),
    path("upload_game/", views.FailedGameUploadView.as_view(), name="upload_game"),
    path("players/", views.PlayerListView.as_view(), name="player_list"),
    path("players/<int:pk>/", views.PlayerDetailView.as_view(), name="player_detail"),
    path("ranking/", views.RankingView.as_view(), name="ranking"),
    path("settings/", views.UserSettingsView.as_view(), name="settings"),
    path("stats/", views.StatsView.as_view(), name="stats"),
    path("login/", views.MyLoginView.as_view(), name="login"),
    path("logout/", views.MyLogoutView.as_view(), name="logout"),
    path(
        "login/password_reset/",
        views.MyPasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "login/password_reset/done/",
        views.MyPasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "login/password_reset/<uidb64>/<token>/",
        views.MyPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "login/password_reset/complete/",
        views.MyPasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
]

web/forms.py
import base64
from io import BytesIO

from django import forms
from django.contrib.auth.password_validation import (
    get_default_password_validators,
    validate_password,
)
from PIL import Image

from games.models import User

from .models import FailedGameUpload

validators_help_text = "<br>".join(
    [v.get_help_text() for v in get_default_password_validators()]
)


class UserSettingsForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            "username",
            "email",
            "new_password",
            "new_image_data_url",
            "image_deleted",
        ]

    new_password = forms.CharField(
        widget=forms.PasswordInput, required=False, help_text=validators_help_text
    )
    new_image_data_url = forms.CharField(required=False)
    image_deleted = forms.BooleanField(required=False)

    def clean_username(self):
        username = self.cleaned_data["username"]
        if (
            User.objects.filter(username__iexact=username)
            .exclude(id=self.instance.id)
            .exists()
        ):
            raise forms.ValidationError("A user with that username already exists.")

        return username

    def clean_new_image_data_url(self):
        data_url = self.cleaned_data["new_image_data_url"]
        if not data_url:
            self.cleaned_data["image_io"] = None
            return

        parts = data_url.split("base64,", maxsplit=1)
        if len(parts) != 2:
            raise forms.ValidationError("Invalid data url")

        try:
            data = base64.b64decode(parts[1])
        except Exception:
            raise forms.ValidationError("Invalid base64 data")

        bytes_io = BytesIO(data)
        try:
            image = Image.open(bytes_io)
            image.verify()
        except Exception:
            raise forms.ValidationError("Invalid image")

        bytes_io.seek(0)
        self.cleaned_data["image_io"] = bytes_io

    def clean_new_password(self):
        password = self.cleaned_data["new_password"]
        if password:
            validate_password(password, self.instance)

        return password


class FailedGameUploadForm(forms.ModelForm):
    class Meta:
        model = FailedGameUpload
        fields = ["game_log_file", "game_log", "notes"]

    game_log_file = forms.FileField(required=False)

web/templates/base.html
{% load static %}
{% load bootstrap4 %}
{% load webpush_notifications %}
<!doctype html>
<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>{% block pagetitle %}Page{% endblock %} | Academy</title>
		<link rel="shortcut icon" href="{% static "favicon.ico" %}" type="image/x-icon">
		<link rel="alternate" type="application/rss+xml" title="Academy games" href="/games/rss/">
		<meta name="theme-color" content="#343a40">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
		<link rel="stylesheet" href="{% static "css/styles.css" %}">

		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/apexcharts/3.19.0/apexcharts.min.css" integrity="sha256-RUxywoyKDxPwo7mk/9S7TvbhR+IpVsldMi53nTNGpWQ=" crossorigin="anonymous" />

		<link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
  integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
  crossorigin=""/>

		<style>
		#banner {
			width: 100%;
			background-color: {{ config.BANNER_COLOR }};
			display: flex;
			justify-content: center;
			align-items: center;
			font-size: 2em;
			margin: -1em 0 1em 0;
			padding: 1em;
			text-align: center;
		}
		{% if config.BANNER_BLINK %}
		#banner a {
			color: #000;
			animation: blinker 2s linear infinite;
		}
		@keyframes blinker {
			50% {
				color: white;
			}
		}
		{% endif %}
		</style>

		{% block styles %}{% endblock %}

    <script>
      var _isPushEnabled;
      var notificationButton;
      var notificationButtonClicked = false;

      function updateNotificationButton() {
        if (_isPushEnabled) {
          notificationButton.classList.add("subscribed");
        } else {
          notificationButton.classList.remove("subscribed");
        }
      }

      Object.defineProperty(window, 'isPushEnabled', {
        get: function() { return _isPushEnabled; },
        set: function(v) {
          _isPushEnabled = v;

          if (notificationButton) {
            updateNotificationButton();
          }
        }
      });

      window.addEventListener("DOMContentLoaded", function() {
        var webpushButton = document.getElementById("webpush-subscribe-button");
        notificationButton = document.getElementById("notification-button");
        notificationButton.addEventListener("click", function() {
          notificationButtonClicked = true;
          if (!registration) {
            showMessage('Service Worker is not supported in your Browser!');
            return;
          }
          webpushButton.click();
        });
        updateNotificationButton();
      });
    </script>
    <style>
      #notification-button.subscribed .fa-bell {
        display: none;
      }
      #notification-button:not(.subscribed) .fa-bell-slash {
        display: none;
      }
    </style>
    {% webpush_header %}
    <script>
      function showMessage(message) {
        if (notificationButtonClicked) {
          alert(message);
        }
      }
    </script>
	</head>
	<body class="{% if user.is_staff %}staff-user{% endif %}">
    <div style="display: none;">
      {% webpush_button %}
    </div>

		{% block body %}{% endblock %}

		{% include "footer.html" %}

		<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js" integrity="sha256-4iQZ6BVL4qNKlQ27TExEhBN1HFPvAvAMbFavKKosSWQ=" crossorigin="anonymous"></script>

		<script src="https://cdnjs.cloudflare.com/ajax/libs/apexcharts/3.19.0/apexcharts.min.js" integrity="sha256-cre9IYMCEv8sI80be7MYT2DRSQqnGayjkSV8HhP3/tM=" crossorigin="anonymous"></script>

		<script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"
  integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew=="
  crossorigin=""></script>

		{% if config.SNOWFLAKES_ENABLED %}
    <script src="https://unpkg.com/magic-snowflakes@4.1.6/dist/snowflakes.min.js" integrity="sha384-jbAIB/GHy9b9yhKXwiySc2MYlOgy9yalQPKzgZ8wx0dror6JrgWh+6VEXX2aGQ1i" crossorigin="anonymous"></script><script src="https://unpkg.com/magic-snowflakes@4.1.6/dist/snowflakes.min.js" integrity="sha384-jbAIB/GHy9b9yhKXwiySc2MYlOgy9yalQPKzgZ8wx0dror6JrgWh+6VEXX2aGQ1i" crossorigin="anonymous"></script>
    <script>
      Snowflakes({
        count: {{ config.SNOWFLAKES_COUNT }},
      });
    </script>
		{% endif %}

		<script src="{% static "js/script.js" %}"></script>
		{% block scripts %}{% endblock %}

    <script data-goatcounter="https://academy.goatcounter.com/count"
        async src="//gc.zgo.at/count.js"></script>
	</body>
</html>

web/templates/container.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block body %}
<div class="wrapper">
    {% include "nav.html" %}

    <main class="container">
        {% bootstrap_messages %}
        {% block content %}{% endblock %}
    </main>

    <div class="push"></div>
</div>

{% endblock %}

web/templates/game_detail.html
{% extends "base.html" %}

{% load svelte %}

{% block pagetitle %}Game {{ object.id }}{% endblock %}

{% block styles %}
<style>
    body {
        display: flex;
        flex-direction: column;
    }

    nav {
        margin-bottom: 0px !important;
        flex-grow: 0;
    }

    #svelte-game_detail {
        height: calc(100% - 64px);
    }

    .card-img-top {
        width: {{ IMAGE_WIDTH }}px;
    }
</style>
<script>
    window.is_authenticated = {{ user.is_authenticated|lower }};
    window.is_staff = {{ user.is_staff|lower }};
</script>

{% svelte_include "GameDetail" %}

{% endblock %}

{% block body %}

{% include "nav.html" %}

{{ game_data|json_script:"game_data" }}
{{ ordered_gameplayers|json_script:"ordered_gameplayers" }}
{{ card_constants|json_script:"card_constants" }}

<div id="svelte-game_detail">
</div>

{% endblock %}

web/templates/index.html
{% extends "container.html" %}

{% load static %}
{% load humanize %}

{% block pagetitle %}Frontpage{% endblock %}

{% block content %}

<h5><i class="fas fa-chart-pie"></i> General Stats</h5>

<hr>

<div class="container">
    <div class="row">
        <div class="card col-md-3 m-auto">
            <div class="card-body text-center">
                <i class="fas fa-gamepad fa-3x"></i>
                <p class="card-title">Games played</p>
                <h4 class="card-text">{{ total_games|intcomma }}</h4>
            </div>
        </div>
        <div class="card col-md-3 m-auto">
            <div class="card-body text-center">
                <i class="fas fa-beer fa-3x"></i>
                <p class="card-title">Beers consumed</p>
                <h4 class="card-text">{{ total_beers|floatformat:0|intcomma }}</h4>
            </div>
        </div>
        <div class="card col-md-3 m-auto">
            <div class="card-body text-center">
                <i class="fas fa-calendar-alt fa-3x"></i>
                <p class="card-title">Current season</p>
                <h4 class="card-text">{{ current_season.number }}</h4>
            </div>
        </div>
    </div>
</div>

{% if live_games %}

<br>
<h5><i class="fas fa-hand-spock"></i> Live Games</h5>

<hr>

{% for game in live_games %}
<div class="card mt-1 mb-1 hover bg-danger text-light" data-href="/games/{{ game.id }}/">
    <div class="container p-3">
        <i class="far fa-user" style="margin-right: 5px;"></i>

        {% for player in game.ordered_players %}
        <a href="/players/{{ player.id }}/" class="text-light">{{ player.username }}</a>{% if not forloop.last %},{% endif %}
        {% endfor %}

        <div class="float-right col-md-auto p-0 live" data-start-time="{{ game.start_datetime.timestamp }}">
            <i class="far fa-clock d-lg-none"></i>
            <div class="duration" style="display: inline;">
                {{ game.duration_str }}
            </div>
            <i class="far fa-clock d-none d-lg-inline" style="margin-left: 5px;"></i>
        </div>
    </div>
</div>

{% endfor %}

{% endif %}

<br>
<h5><i class="fas fa-heart"></i> Recently Active Players</h5>

<hr>

<div class="row">
    {% for user, reason in recent_players %}
    <div class="col-6 col-lg-3 py-2" title="{{ reason }}">
        <a href="/players/{{ user.id }}/"><img src="{{ user.image_url }}"
                class="img-fluid mx-auto d-block bottom-shadow rounded"></a>
        <div class="card-username">{{ user.username }}</div>
    </div>
    {% endfor %}
</div>

<br>

<h5><i class="fas fa-thumbs-down"></i> Wall Of Shame</h5>

<hr>

<div class="row">
    {% for user, reason in wall_of_shame_players %}
    <div class="col-6 col-lg-3 py-2" title="{{ reason }}">
        <a href="/players/{{ user.id }}/"><img src="{{ user.image_url }}" class="img-fluid mx-auto d-block rounded"></a>
        <div class="card-username">{{ user.username }}</div>
    </div>
    {% endfor %}
</div>

<style>
    .card-username {
        text-align: center;
        color: #fff;
        font-weight: bold;
        margin-top: -40px;
        font-size: 24px;

        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;

        text-shadow:
            -1px -1px 0 #000,
            1px -1px 0 #000,
            -1px 1px 0 #000,
            1px 1px 0 #000;
    }

    .hover {
    }

    .hover:hover {
        cursor: pointer;
    }
</style>

{% endblock %}

web/templates/login.html
{% extends "container.html" %}

{% load static %}
{% load bootstrap4 %}

{% block pagetitle %}Login{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="mx-auto card col-md-6">
			<div class="card-body">
				<h3 class="card-title">Login</h3>
				<hr>
				<form action="/login/" method="post" class="form">
					{% csrf_token %}
					{% bootstrap_form form %}
					{% buttons %}
					<br>
					<button type="submit" class="btn btn-danger col-12 text-big" style="font-size: 18px;">Login</button>
					<br><br>
					<div class="text-center">
						<a href="{% url 'password_reset' %}">Forgotten your password?</a>
						<br>
						<a href="{{ PLAY_URL }}">Register new user</a>
					</div>
					{% endbuttons %}
				</form>
			</div>
		</div>
	</div>
</div>

<audio id="oops" preload="auto">
	<source src="{% static "sound/oops.ogg" %}" type="audio/ogg; codecs=vorbis">
	<source src="{% static "sound/oops.mp3" %}" type="audio/mpeg">
</audio>
{% endblock %}

{% block scripts %}
<script>
	if($(".alert-danger").length > 0){
		$("#oops").get(0).play();
	}
</script>
{% endblock %}

web/templates/nav.html
{% load static %}
{% load bootstrap4 %}
{% load webpush_notifications %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
    <div class="container">
        <a class="navbar-brand" href="/">
            <img src="{% static "logo.png" %}" width="32px" class="d-inline-align-top">
            Academy
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                {% if user.is_staff %}
                    <a class="nav-item nav-link" href="{{ admin_url }}">Admin<i class="fas fa-tools float-right d-lg-none"></i></a>
                {% endif %}
                <a class="nav-item nav-link" href="/games/">Games<i class="fas fa-gamepad float-right d-lg-none"></i></a>
                <a class="nav-item nav-link" href="/players/">Players<i class="fas fa-users float-right d-lg-none"></i></a>
                <a class="nav-item nav-link" href="/ranking/">Ranking<i class="fas fa-trophy float-right d-lg-none"></i></a>
                <a class="nav-item nav-link" href="/stats/">Stats<i class="fas fa-info-circle float-right d-lg-none"></i></a>
                <a class="nav-item nav-link" href="/about/">About<i class="fas fa-info-circle float-right d-lg-none"></i></a>
                {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="/players/{{ user.id }}/">My Profile<i class="fas fa-user float-right d-lg-none"></i></a>
                    <form action="/logout/" method="POST" style="align-self: center;">
                        {% csrf_token %}
                        <button class="nav-item nav-link" type="submit" style="display: contents;">
                            Logout ({{ user.get_username }})
                            <i class="fas fa-sign-out-alt float-right d-lg-none"></i>
                        </button>
                    </form>
                {% else %}
                    <a class="nav-item nav-link" href="/login/">Login<i class="fas fa-sign-in-alt float-right d-lg-none"></i></a>
                {% endif %}
                <a class="nav-item nav-link d-lg-none" href="{{ PLAY_URL }}">Play!<i class="fas fa-play float-right"></i></a>
            </div>
        </div>
        <span id="notification-button" class="text-light text-bg btn btn-lg" style="margin-right: -15px;">
          <i class="fas fa-bell" title="Notify me when games start"></i>
          <i class="fas fa-bell-slash" title="Unsubscribe from notifications"></i>
        </span>
        <a class="btn btn-lg" href="/games/rss/"><i class="fas fa-rss" style="color: #ee802f;"></i></a>
        <a href="{{ PLAY_URL }}" class="btn btn-danger btn-lg active d-none d-lg-block" role="button" aria-pressed="true">Play!</a>
    </div>
</nav>

{% if config.BANNER_ENABLED %}
<div id="banner">
    <a href="{{ config.BANNER_URL }}">
        {{ config.BANNER_TEXT }}
    </a>
</div>
{% endif %}

web/templates/password_reset.html
{% extends "container.html" %}

{% load static %}
{% load bootstrap4 %}

{% block pagetitle %}Reset password{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="mx-auto card col-md-6">
			<div class="card-body">
				<h3 class="card-title">Reset password</h3>
				<hr>
				<form method="post" class="form">
					{% csrf_token %}
					{% bootstrap_form form %}
					{% buttons %}
					<br>
					<button type="submit" class="btn btn-danger col-12 text-big" style="font-size: 18px;">Submit</button>
					{% endbuttons %}
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

web/templates/password_reset_complete.html
{% extends "container.html" %}

{% load static %}
{% load bootstrap4 %}

{% block pagetitle %}Password reset completed{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="mx-auto card col-md-6">
			<div class="card-body">
				<h3 class="card-title">Password changed</h3>
				<hr>
				<a class="btn btn-danger col-md-12" href="/login/">Go to login page</a>
			</div>
		</div>
	</div>
</div>
{% endblock %}

web/templates/password_reset_confirm.html
{% extends "container.html" %}

{% load static %}
{% load bootstrap4 %}

{% block pagetitle %}Password reset confirmation{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="mx-auto card col-md-6">
			<div class="card-body">
				<h3 class="card-title">New password</h3>
				<hr>
				{% if form %}
					<form method="post" class="form">
						{% csrf_token %}
						{% bootstrap_form form %}
						{% buttons %}
						<br>
						<button type="submit" class="btn btn-danger col-12 text-big" style="font-size: 18px;">Submit</button>
						{% endbuttons %}
					</form>
				{% else %}
					<p>Invalid password reset link. <a href="/login/password_reset/">Try again?</a></p>
				{% endif %}
			</div>
		</div>
	</div>
</div>
{% endblock %}

web/templates/password_reset_done.html
{% extends "container.html" %}

{% load static %}
{% load bootstrap4 %}

{% block pagetitle %}Password reset email sent{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="mx-auto card col-md-6">
			<div class="card-body">
				<h3 class="card-title">Email sent</h3>
				<hr>
				<p>An email with a password reset link has been sent.</p>
			</div>
		</div>
	</div>
</div>
{% endblock %}

web/templates/player_list.html
{% extends "paginated_list_view.html" %}

{% block pagetitle %}Players{% endblock %}

{% block beforetable %}
<h2><i class="fas fa-users"></i> Players</h2>

<form method="get">
	<div class="form-group">
		<input type="text" name="query" class="form-control" placeholder="Search" value="{{ query }}" autofocus>
	</div>
</form>
{% endblock %}

{% block thead %}
<tr class="academy-table">
	<th scope="col"></th>
	<th scope="col">Username</th>
	<th scope="col">Games in {{ current_season }}</th>
	<th scope="col">Total Games</th>
</tr>
{% endblock %}

{% block tbody %}
{% for user in object_list %}
<tr data-href="/players/{{ user.id }}/" class="academy-table">
	<td>
		<div class="round-image" style="background-image: url({{ user.image_url }});"></div>
	</td>
	<td><span class="username">{{ user.username }}</span></td>
	<td>{{ user.current_season_game_count }}</td>
	<td>{{ user.total_game_count }}</td>
</tr>
{% endfor %}
{% endblock %}

web/templates/user_settings.html
{% extends "container.html" %}

{% load static %}
{% load bootstrap4 %}

{% block pagetitle %}Settings{% endblock %}

{% block styles %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.5/cropper.min.css" integrity="sha256-mS+0WtWHI0Mw4UuIK5xU+b+pB/vfWZiEHV4sJWx7az8=" crossorigin="anonymous" />
<style>
#image {
	max-width: 100%;
}
</style>
{% endblock %}

{% block content %}

<h3>
	<i class="fas fa-cogs"></i> Settings
</h3>

<hr>

<form method="post">
	{% csrf_token %}
	<div style="display: none;">
		<input type="file" id="file_input" accept="image/*" style="display: none;">
		{{ form.new_image_data_url }}
		{{ form.image_deleted }}
	</div>
	<div class="row">
		<div class="col-md-6 text-center">
			<div style="margin: 0px 20%;">
				<img src="{{ object.image_url }}" id="image" width="{{ IMAGE_WIDTH }}" height="{{ IMAGE_HEIGHT }}" alt="Profile picture">
			</div>
			<br>
			<button type="button" id="upload_button" class="btn btn-primary col-md-3">Upload image</button>
			<div class="d-lg-none" style="height: 10px;"></div>
			<button type="button" id="delete_button" class="btn btn-danger col-md-3">Delete</button>
			<br class="d-lg-none">
			<br class="d-lg-none">
		</div>
		<div class="col-md-6">
			{% bootstrap_field form.username %}
			{% bootstrap_field form.email %}
			<hr>
			{% bootstrap_field form.new_password %}
		</div>
	</div>

	<hr>
	<div class="text-right">

		<button type="submit" class="btn btn-primary col-md-1 pull-right">Save</button>
		<div class="d-lg-none" style="height: 10px;"></div>
		<a href="/players/{{object.id}}/" class="btn btn-danger col-md-1">Cancel</a>
	</div>
</form>
{% endblock %}

{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/1.5.5/cropper.min.js" integrity="sha256-vshROrHusjRqmlrpFKS7oAAd4YV7Stzn6DlDmtIBG/4=" crossorigin="anonymous"></script>
<script>
	var image = document.getElementById("image");
	var initialImageSrc = image.src;

	function updateCropped() {
		var new_url = cropper.getCroppedCanvas().toDataURL("image/png");
		$("#id_new_image_data_url").val(new_url);
	}

	var cropper = new Cropper(image, {
		aspectRatio: {{ IMAGE_WIDTH }} / {{ IMAGE_HEIGHT }},
		autoCropArea: true,
	});

	image.addEventListener("cropend", updateCropped);

	image.addEventListener("ready", function() {
		if (image.src !== initialImageSrc) {
			updateCropped();
		}
	});

	var file_input = $("#file_input");
	$("#upload_button").click(function() {
		file_input.click();
	});
	$("#delete_button").click(function() {
		cropper.replace("{% static "user.png" %}");
		$("#id_new_image_data_url").val("");
		$("#id_image_deleted").prop("checked", true);
	});
	file_input.change(function() {
		var files = file_input.get(0).files;
		if (files.length > 0) {
			var file = files[0];
			var reader = new FileReader();
			reader.readAsDataURL(file);
			reader.onload = function(evt) {
				if(evt.target.readyState === FileReader.DONE) {
					var url = evt.target.result;
					cropper.replace(url);
					$("#id_image_deleted").prop("checked", false);
				}
			};
		}
	});
</script>
{% endblock %}